server.port=8080

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/campusdb}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false

app.jwt.secret=${JWT_SECRET:change-me-please-change-me-please-change-me}
app.jwt.expiration-minutes=${JWT_EXP_MINUTES:120}

logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=INFO